### ISSUE TITLE
Dataset throws serialization issue during interpretation

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#199]
**datasetKey** -> 95db4db8-f762-11e1-a439-00145eb45e9a
**hdfs url** -> /data/ingest/95db4db8-f762-11e1-a439-00145eb45e9a/114

**Start command:**
`sudo -u hdfs spark2-submit --conf spark.metrics.conf=/home/crap/config/metrics.properties --conf "spark.driver.extraClassPath=/home/crap/lib/logstash-gelf.jar" --driver-java-options "-Dlog4j.configuration=file:/home/crap/config/log4j-interpretation-pipeline.properties" --queue root.pipelines --conf spark.default.parallelism=440 --conf spark.executor.memoryOverhead=4096 --conf spark.yarn.maxAppAttempts=1 --conf spark.dynamicAllocation.enabled=false --conf "spark.executor.extraJavaOptions=-XX:+UseG1GC" --class org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline --master yarn --deploy-mode cluster --executor-memory 6G --executor-cores 5 --num-executors 44 --driver-memory 1G hdfs://ha-nn/pipelines/jars/ingest-gbif.jar --datasetId=95db4db8-f762-11e1-a439-00145eb45e9a --attempt=114 --interpretationTypes=ALL --runner=SparkRunner --targetPath=hdfs://ha-nn/data/ingest --metaFileName=verbatim-to-interpreted.yml --inputPath=hdfs://ha-nn/data/ingest/95db4db8-f762-11e1-a439-00145eb45e9a/114/verbatim.avro --avroCompressionType=SNAPPY --avroSyncInterval=2097152 --hdfsSiteConfig=/home/crap/config/hdfs-site.xml --coreSiteConfig=/home/crap/config/core-site.xml --properties=/home/crap/config/pipelines.properties --endPointType=DWC_ARCHIVE --tripletValid=false --occurrenceIdValid=true`

**Error:**
```
19/07/18 14:55:45 INFO yarn.Client: 
	 client token: N/A
	 diagnostics: User class threw exception: org.apache.beam.sdk.Pipeline$PipelineExecutionException: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
extensions (org.gbif.pipelines.io.avro.ExtendedRecord)
value (org.apache.beam.sdk.util.WindowedValue$TimestampedValueInGlobalWindow)
	at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:67)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:98)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:86)
	at org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline.run(VerbatimToInterpretedPipeline.java:189)
	at org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline.main(VerbatimToInterpretedPipeline.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
extensions (org.gbif.pipelines.io.avro.ExtendedRecord)
value (org.apache.beam.sdk.util.WindowedValue$TimestampedValueInGlobalWindow)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:551)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
	at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:278)
	at org.apache.spark.serializer.DeserializationStream$$anon$1.getNext(Serializer.scala:168)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:30)
	at org.apache.beam.runners.spark.translation.SparkProcessContext$ProcCtxtIterator.computeNext(SparkProcessContext.java:135)
	at org.apache.beam.vendor.guava.v20_0.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at org.apache.beam.vendor.guava.v20_0.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:30)
	at org.apache.beam.runners.spark.translation.SparkProcessContext$ProcCtxtIterator.computeNext(SparkProcessContext.java:135)
	at org.apache.beam.vendor.guava.v20_0.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at org.apache.beam.vendor.guava.v20_0.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:216)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.avro.generic.GenericData$Array.add(GenericData.java:275)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:790)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:161)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:708)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	... 54 more

	 ApplicationMaster host: 130.225.43.91
	 ApplicationMaster RPC port: 0
	 queue: root.pipelines
	 start time: 1563461608953
	 final status: FAILED

```

**Comment by muttcg** [comment]
One more dataset -> b5cdf794-8fa4-4a85-8b26-755d087bf531

**Comment by muttcg** [comment]
Fixed crawler app memory settings

**Comment by asturcon** [comment]
Still happening: https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:AWBa0XR-f8lu3pmE7ete,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'datasetId:%2215f819bd-6612-4447-854b-14d12ee1022d%22%20AND%20attempt:%22112%22')),sort:!('@timestamp',desc))

**Comment by asturcon** [comment]
another case: http://c5master2-vh.gbif.org:8088/cluster/app/application_1561148256758_55246

Command
`
sudo -u hdfs spark2-submit --conf spark.metrics.conf=/home/crap/config/metrics.properties --conf "spark.driver.extraClassPath=/home/crap/lib/logstash-gelf.jar" --driver-java-options "-Dlog4j.configuration=file:/home/crap/config/log4j-interpretation-pipeline.properties" --queue root.pipelines --conf spark.default.parallelism=70 --conf spark.executor.memoryOverhead=4096 --conf spark.yarn.maxAppAttempts=1 --conf spark.dynamicAllocation.enabled=false --conf "spark.executor.extraJavaOptions=-XX:+UseG1GC" --class org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline --master yarn --deploy-mode cluster --executor-memory 6G --executor-cores 5 --num-executors 7 --driver-memory 1G hdfs://ha-nn/pipelines/jars/ingest-gbif.jar --datasetId=7e380070-f762-11e1-a439-00145eb45e9a --attempt=128 --interpretationTypes=ALL --runner=SparkRunner --targetPath=hdfs://ha-nn/data/ingest --metaFileName=verbatim-to-interpreted.yml --inputPath=hdfs://ha-nn/data/ingest/7e380070-f762-11e1-a439-00145eb45e9a/128/verbatim.avro --avroCompressionType=SNAPPY --avroSyncInterval=2097152 --hdfsSiteConfig=/home/crap/config/hdfs-site.xml --coreSiteConfig=/home/crap/config/core-site.xml --properties=/home/crap/config/pipelines.properties --endPointType=DWC_ARCHIVE --tripletValid=false --occurrenceIdValid=false
`

**Comment by asturcon** [comment]
One more: http://c5master2-vh.gbif.org:19888/jobhistory/logs/c6n1.gbif.org:8041/container_1561148256758_70888_01_000001/container_1561148256758_70888_01_000001/hdfs/stderr/?start=0

It was run with:
`
sudo -u hdfs spark2-submit --conf spark.metrics.conf=/home/crap/config/metrics.properties --conf "spark.driver.extraClassPath=/home/crap/lib/logstash-gelf.jar" --driver-java-options "-Dlog4j.configuration=file:/home/crap/config/log4j-interpretation-pipeline.properties" --queue root.pipelines --conf spark.default.parallelism=440 --conf spark.executor.memoryOverhead=4096 --conf spark.yarn.maxAppAttempts=1 --conf spark.dynamicAllocation.enabled=false --conf "spark.executor.extraJavaOptions=-XX:+UseG1GC" --class org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline --master yarn --deploy-mode cluster --executor-memory 44G --executor-cores 5 --num-executors 44 --driver-memory 1G hdfs://ha-nn/pipelines/jars/ingest-gbif.jar --datasetId=95db4db8-f762-11e1-a439-00145eb45e9a --attempt=116 --interpretationTypes=ALL --runner=SparkRunner --targetPath=hdfs://ha-nn/data/ingest --metaFileName=verbatim-to-interpreted.yml --inputPath=hdfs://ha-nn/data/ingest/95db4db8-f762-11e1-a439-00145eb45e9a/116/verbatim.avro --avroCompressionType=SNAPPY --avroSyncInterval=2097152 --hdfsSiteConfig=/home/crap/config/hdfs-site.xml --coreSiteConfig=/home/crap/config/core-site.xml --properties=/home/crap/config/pipelines.properties --endPointType=DWC_ARCHIVE --tripletValid=false --occurrenceIdValid=true
`

**Comment by asturcon** [comment]
Fixed by 2 attempts in yarn (it's the default value in our cluster). https://github.com/gbif/crawler/commit/32f8f2888cb35a2b4cf3c4300dad047e0dd39f52

**Comment by asturcon** [comment]
Still happening: http://c5master2-vh.gbif.org:8088/cluster/app/application_1561148256758_77787

**Comment by muttcg** [comment]
More likely fixed in -> https://github.com/gbif/crawler/commit/5e8ba3e4073223385a1623515d83d193053ec52d
I tested various datasets from 1k to 10m, didn't find a similar issue
